// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/13/2025, 11:51:25 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/workspace/Minabtech_Project/food-recipe-frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/plugins/**/*.{js,ts,mjs}","/workspace/Minabtech_Project/food-recipe-frontend/src/composables/**/*.{js,ts,mjs}","/workspace/Minabtech_Project/food-recipe-frontend/src/utils/**/*.{js,ts,mjs}","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/index.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/recipes/create.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/recipes/edit.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/recipes/index.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/users/[id].vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/admin/users/index.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/index.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/login.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/Signup.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/pages/user-profile.vue","/workspace/Minabtech_Project/food-recipe-frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/Minabtech_Project/food-recipe-frontend/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;